server:
  port: 18090
  servlet:
    context-path: /
  error:
    include-stacktrace: never

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8080/oauth/v2/keys
        opaquetoken:
          introspection-uri: http://localhost:8080/oauth/v2/introspect
          client-id: '<your-client-id>'
          client-secret: '<your-client-secret>'

logging:
  level:
    root: info
    demo: debug
    org:
      springframework:
        web: info
        security: debug
